name: Cleanup Branch Deployment

on:
  pull_request:
    types: [closed]

jobs:
  cleanup-deployment:
    runs-on: ubuntu-latest
    # Only run if PR was actually merged (not just closed)
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove branch deployment directory
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          echo "Cleaning up deployment for branch: $BRANCH_NAME"

          # Check if directory exists
          if [ -d "$BRANCH_NAME" ]; then
            echo "Directory $BRANCH_NAME exists, removing it..."
            rm -rf "$BRANCH_NAME"
            
            # Configure git
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            
            # Commit and push the removal
            git add .
            git commit -m "🗑️ Cleanup: Remove deployment for merged branch '$BRANCH_NAME'" || echo "Nothing to commit"
            git push origin gh-pages
            
            echo "✅ Successfully removed deployment directory: $BRANCH_NAME"
          else
            echo "ℹ️ Directory $BRANCH_NAME does not exist, nothing to clean up"
          fi

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            const branchName = context.payload.pull_request.head.ref;
            const message = `🗑️ **Deployment Cleanup**

            The deployment for branch \`${branchName}\` has been automatically removed from GitHub Pages after merge.

            Main documentation is still available at: https://hung-theinfitech.github.io/Github-Page-Demo/`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
