name: Deploy AsyncAPI Docs

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - dev
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # OpenAPIドキュメント用の依存関係をインストール
      - name: Install Swagger UI CLI
        run: npm install -g swagger-cli

      # # bufcliをインストール
      # - name: Install buf CLI
      #   run: |
      #     curl -sSL "https://github.com/bufbuild/buf/releases/latest/download/buf-Linux-x86_64" -o /usr/local/bin/buf
      #     chmod +x /usr/local/bin/buf
      #     buf --version

      # # Googleの標準protobufライブラリをクローン
      # - name: Clone googleapis repo (third party deps)
      #   run: |
      #     if [ ! -d "third_party/googleapis" ]; then
      #       git clone https://github.com/googleapis/googleapis.git third_party/googleapis
      #     fi

      # # OpenAPIドキュメントを生成する
      # - name: Generate OpenAPI JSON with buf
      #   working-directory: proto
      #   run: |
      #     buf mod update
      #     buf generate

      # # OpenAPIドキュメントをSwagger UI で生成
      # - name: Generate HTML docs from OpenAPI JSON
      #   run: |
      #     mkdir -p public
      #     cp proto/gen/proto/openapi.swagger.json docs/openapi.json

      # `gh-pages` ブランチにデプロイ (dev branch) or `{branch}-review` ブランチにデプロイ (other branches)
      - name: Deploy to GitHub Pages (dev branch)
        if: github.ref_name == 'dev'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages

      - name: Deploy to GitHub Pages (other branches)
        if: github.ref_name != 'dev'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages
          destination_dir: ${{ github.ref_name }}
