name: Deploy AsyncAPI Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Node.js をセットアップ
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # OpenAPIドキュメント用の依存関係をインストール
      - name: Install Swagger UI CLI
        run: npm install -g swagger-cli redoc-cli

      # OpenAPIドキュメントをSwagger UI で生成
      # - name: Generate OpenAPI Docs (Doc2 with Redoc)
      #   run: redoc-cli bundle backend/docs/03_webApp_IF/API.yaml -o public/backend/webapi.html

      # `gh-pages` ブランチにデプロイ
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
