name: Update PR Template Placeholders

on:
  pull_request:
    types: [opened]

jobs:
  replace-placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Replace __BRANCH__ in PR body
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const branch = pr.head.ref;
            const updatedBody = pr.body.replace(/__BRANCH__/g, branch);

            if (updatedBody !== pr.body) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                body: updatedBody
              });
            }
